### ISSUE TITLE
Client code

### ISSUE THREAD

**Issue by AkshayGupta94** [thisisfatih/applicationKey#1]
In the client code
 public static MobileServiceClient MobileService =
            new MobileServiceClient(
           keys.url,new AppKeyHandler()
        );
is enough.. we can not send the key in this MobileServiceClient . and it still works

**Comment by thisisfatih** [comment]
Hi Akshay,

Thanks for the warning, I uploaded this part according to following information.

Here is the situation, if you are using Azure Mobile Services (now it is deprecated)  package you need to write key because of class definition, but if you are using Azure Mobile App Client package as you said application url and Application Key Handler is enough.

Fatih.
