### ISSUE TITLE
anonymous or authenticated

### ISSUE THREAD

**Issue by akivamier** [thisisfatih/applicationKey#2]
Thank you for this information!  But you mention setting permissions to "anonymous", however, anonymous doesn't require permissions.  Did you mean don't forget to change permissions to "authenticated?"

Thanks Again!

**Comment by thisisfatih** [comment]
No, permission needs to be “Anonymous” because if you select Authenticated, clients need to authenticate themselves first, then they can use application key. Application key system lets to access everyone who has the application key of the system.
This type of connection establishment is suitable for like systems have its own registration and login system other than (Facebook, twitter etc. login) or systems not using any registration or login system.
P.S. You can use authentication and application key at the same time. That provides double protection.

Fatih.

**Comment by akivamier** [comment]
Hey Fatih,

 

Understood, thanks for taking the time to reply!

**Comment by thisisfatih** [comment]
welcome ;)
